export const CREATE_PROJECT = 'CREATE_PROJECT'

export const DELETE_PROJECT = 'DELETE_PROJECT'

export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR'

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'

export const SIGN_OUT = 'SIGN_OUT'
